### ISSUE TITLE
Error message fails to identify missing slash after -o parameter

### ISSUE THREAD

**Issue by sankalpshere** [tableau/octopus-python-client#2]
```
octopus_python_client -n=octopus_demo_server -o=http://octopus-cloud-eng.tsi.lan/api -k=<API_KEY> -s=<Space_Id> -a=get_types
```

Throws error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/octopus_python_client", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/octopus_python_client/main.py", line 263, in main
    run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/octopus_python_client/main.py", line 167, in run
    raise ValueError(f"the space id/name {args.space_id_name} you specified does not exist "
ValueError: the space id/name <Space_Id you specified does not exist or you may not have permission to access it
```

Real error is `/` is missing after `/api` in Octopus server URL.

**Comment by tonythebest** [comment]
will be fixed by https://github.com/tableau/octopus-python-client/pull/3
