### ISSUE TITLE
Linux: client is trying to modify configuration.json

### ISSUE THREAD

**Issue by tableau2kube** [tableau/octopus-python-client#8]
On Linux the client is trying to modify configuration.json. User configuration should not be stored there, it should rather use `~/.octopus_python_client.json`. 

```bash
sudo pip install octopus_python_client
```

```bash
~>octopus_python_client -o https://octopus-cloud-eng.tsi.lan/api/ -k $OCTOPUS_APIKEY -a get_spaces                                                                                                                                                          
Traceback (most recent call last):
  File "/usr/local/bin/octopus_python_client", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/octopus_python_client/main.py", line 341, in main
    OctopusClient().run()
  File "/usr/local/lib/python3.6/site-packages/octopus_python_client/main.py", line 246, in run
    args = self._process_args_to_configs()
  File "/usr/local/lib/python3.6/site-packages/octopus_python_client/main.py", line 241, in _process_args_to_configs
    self._target_config.save_config()
  File "/usr/local/lib/python3.6/site-packages/octopus_python_client/config.py", line 108, in save_config
    save_file(file_path_name=self.config_file, content=config_dict)
  File "/usr/local/lib/python3.6/site-packages/octopus_python_client/utilities/helper.py", line 173, in save_file
    save_json_file(file_path_name=file_path_name, content=content)
  File "/usr/local/lib/python3.6/site-packages/octopus_python_client/utilities/helper.py", line 88, in save_json_file
    with open(file_path_name, 'w', newline='\n') as fp:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/site-packages/octopus_python_client/configurations/configuration.json'
````

**Comment by tonythebest** [comment]
Hi @tableau2kube , thank you for testing it on Linux and raise the issue. Can you help fix it? Thanks again.
